mpc_update_frequency: 60
tf_update_frequency: 60
max_linear_velocity: 0.2
max_angular_velocity: 0.2
control_loop_frequency: 100
default_external_force: [0, 0, 0]
default_external_torque: [0, 0, 0]
world_frame: odom
tsdf_voxel_size: 0.05
tsdf_voxels_per_side: 16
collision_points: [[[1.0,0.23],[1.0,0.23],[1.0,0.23],[1.0,0.23],[1.0,0.23],[1.0,0.23],[1.0,0.23],[1.0,0.23]],[],[[0.0, 0.1]],[[0.0, 0.1],[0.25,0.07],[0.5,0.07],[0.75,0.07],[1.0,0.09]],[[0.0, 0.09],[0.25,0.07],[0.5,0.07],[0.75,0.07]],[[0.0, 0.07]],[[0.0, 0.07]],[[0.0, 0.08],[1.0,0.08],[1.0,0.08]]]